### ISSUE TITLE
What is Ansible?

### ISSUE THREAD

**Issue by lorenzoromagnoli** [CasaJasmina/CNTRL#1]
@gibix I didn't fully understand what is Ansible. But I guess it is not my business. 
it would be good if Casa Jasmina could become a testbed for some tools that @mastrolinux doesn't has time to test. 
Let's try to discuss with him on the Basecamp strategies and tools we use.

**Comment by lorenzoromagnoli** [comment]
io intanto mi sono guardato [questo](http://www.ansible.com/get-started), credo di aver capito. 
Per installare o configurare, qualunque cosa usiamo solo delle ricette di Ansible. Così a configurare una raspi ci mettiamo 2 minuti invece di qualche ora dove andiamo ad eseguire un comando alla volta. 

#AWESOME

**Comment by gibix** [comment]
Esatto, ieri non ti ho più risposto, ma è un tool che come puoi vedere è facilissimo da implementare e mantenere, che Luca conosce bene.
Pro:
- modulare
- facile (nessun nuovo linguaggio)
- molto diffuso
- scalabile
