### ISSUE TITLE
Mosquitto vs EMQTT

### ISSUE THREAD

**Issue by lorenzoromagnoli** [CasaJasmina/CNTRL#2]
@gibix had a look at [emqtt](https://github.com/emqtt), it looks promising, especially because it already provides a dashboard plugin, the possibility of authentication, and the possibilities of creating new plugins on top of it. 
Can we try it out instead of mosquitto?

**Comment by gibix** [comment]
Sure, I tested emqttd in the last days and looks interesting.
Firstly I write the support for mosquitto (widely used), on the next days the script will support also emqtt.

**Comment by gibix** [comment]
Closed with 05680037af189b6aa6ad55d0cc968e40820e777b
